import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbarm from './compnents/manubare'
import Fotter from './compnents/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'shakir',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='px-4 bg-yellow-50'>
      <Navbarm/>
        {children}
        <Fotter/>  
        </div>
        </body>
    </html>
  )
}
